# Generated by Django 3.0.6 on 2020-05-25 22:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('English Department', 'English Department')], max_length=200)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('take_again_perc', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('difficulty_lvl', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProfRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('difficulty', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('course_name', models.CharField(max_length=200)),
                ('for_credit', models.BooleanField(default=True)),
                ('attendence_req', models.BooleanField(default=True)),
                ('take_again', models.BooleanField(default=False)),
                ('textbook_req', models.BooleanField(default=True)),
                ('comment', models.TextField()),
                ('grade', models.CharField(choices=[('A', 'A')], max_length=1)),
                ('likes_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dislikes_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profrate.Prof')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(choices=[('Computer Science', 'Computer Science')], max_length=200, null=True)),
                ('type', models.CharField(choices=[('Student', 'Student'), ('Professor', 'Professor')], max_length=200)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profrate.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='prof',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profrate.School'),
        ),
    ]
